### PR TITLE
Fix all the shit

### PR DESCRIPTION
**Pull request by msfjarvis**
I'd have liked credit since this is copy of my script which I recommended to @neonkat days ago

### CODE REVIEW

**Comment by aditheking** [comment]
So what u want

**Comment by MSF-Jarvis** [comment]
Delete the repository

**Comment by aditheking** [comment]
WHy

**Comment by MSF-Jarvis** [comment]
Create it again and this time when commiting add --author "MSF Jarvis <
msfjarvis@gmail.com>"

**Comment by neonkat** [comment]
well that escalated quickly.xD

**Comment by MSF-Jarvis** [comment]
Lol yeah, burst of passion 😂

**Pull request merged**
